
export const NUM_CANDIDATES = 120000;
export const NUM_ACTIVE_CANDIDATES = 2000;

export const RENDER_PRECISION = 400;
export const PARTICLE_SIZE = (1 / RENDER_PRECISION) + 0.0001;
export const ACCEPTANCE_THRESHOLD = 0.01;
export const TEMPERATURE_THRESHOLD = 0.1;
export const TEMPERATURE_DECREASE_FACTOR = 0.93;
